import a1a from "./column1/a1a.png";
import a1b from "./column1/a1b.png";
import a2a from "./column1/a2a.png";
import a2b from "./column1/a2b.png";
import a3a from "./column1/a3a.png";
import a3b from "./column1/a3b.png";
import a4a from "./column1/a4a.png";
import a4b from "./column1/a4b.png";
import a5a from "./column1/a5a.png";
import a5b from "./column1/a5b.png";
import b1a from "./column2/b1a.png";
import b1b from "./column2/b1b.png";
import b2a from "./column2/b2a.png";
import b2b from "./column2/b2b.png";
import b3a from "./column2/b3a.png";
import b3b from "./column2/b3b.png";
import b4a from "./column2/b4a.png";
import b4b from "./column2/b4b.png";
import b5a from "./column2/b5a.png";
import b5b from "./column2/b5b.png";
import c1a from "./column3/c1a.png";
import c1b from "./column3/c1b.png";
import c2a from "./column3/c2a.png";
import c2b from "./column3/c2b.png";
import c3a from "./column3/c3a.png";
import c3b from "./column3/c3b.png";
import c4a from "./column3/c4a.png";
import c4b from "./column3/c4b.png";
import c5a from "./column3/c5a.png";
import c5b from "./column3/c5b.png";
import cxa from "./Column01/Column01A.png";
import cxb from "./Column01/Column01B.png";
import cxc from "./Column01/Column01C.png";
import cxd from "./Column01/Column01D.png";
import cxe from "./Column01/Column01E.png";
import cxf from "./Column02/Column02A.png";
import cxg from "./Column02/Column02B.png";
import cxh from "./Column02/Column02C.png";
import cxi from "./Column02/Column02D.png";
import cxj from "./Column02/Column02E.png";
import cxk from "./Column03/Column03A.png";
import cxl from "./Column03/Column03B.png";

const Column01 = [{a1a, a1b}, {cxa}, {a2a, a2b}, {cxb}, {a3a, a3b}, {a4a, a4b},  {cxc},{a5a, a5b}, {cxh}];
const Column02 = [{b1a, b1b}, {cxk},{b2a, b2b}, {cxd}, {b3a, b3b}, {b4a, b4b}, {cxe}, {b5a, b5b}, {cxi}];
const Column03 = [{c1a, c1b}, {cxf}, {c2a, c2b},{cxl}, {c3a, c3b}, {cxg}, {c4a, c4b}, {c5a, c5b}, {cxj}];

export { Column01, Column02, Column03 };
